### PR TITLE
Added dark mode ( fixes #7)

### LINKED ISSUE #7: Improve the dark mode styling
Refine the existing dark mode, ensuring the colors and user experience are cohesive, and make adjustments to the typography, background, and button styles to look great in dark mode.

### PR DESCRIPTION
**Pull request by SohamAP22**
I have added dark mode with changed font. Also fixed an error regarding generate quote script.
image

### CODE REVIEW

**Comment by SohamAP22** [comment]
Sorry, I wasn't assigned the issue, but it was open. So thought of fixing it.

**Comment by DanonymousCoder** [comment]
Pls, try to resolve the conflicts before I can merge

**Comment by stg2209** [comment]
solved and opened a pr (#15) with diff acc.

**Comment by SohamAP22** [comment]
solved and opened a new pr (#18)

**Comment by DanonymousCoder** [comment]
Awesome, don't forget to star the repo.

Thank you!

**Pull request closed without merging**
