### PR TITLE
add like feature

### PR DESCRIPTION
**Pull request by leejieun0000**
I added like feature and  built a page where users can view their favorite list.

### CODE REVIEW

**Comment by leejieun0000** [comment]
Hello~ I would appreciate it if you could give me some feedback on my PR.

**Comment by DanonymousCoder** [comment]
Can you pls share a picture or video of the feature you added?

**Comment by leejieun0000** [comment]
1. added a favorite icon and a My Page icon.
add icons

2. When you generate a quote and click the favorite icon, the icon turns yellow.
image

3. By clicking the My Page icon, you can view the list of favorite quotes.
(You can also remove quotes from the favorites list.)
image

**Review by DanonymousCoder — APPROVED** [review]
Awesome!!!

**Pull request merged**
