### PR TITLE
Added spacing in the container gaps

### PR DESCRIPTION
**Pull request by saikatsardar01**
Please add it

### CODE REVIEW

**Comment by DanonymousCoder** [comment]
Pls follow the  rules and create an issue before a PR

**Comment by saikatsardar01** [comment]
Please mention the process clearly in readme

**Comment by DanonymousCoder** [comment]
Did you read the contributing guidelines at all and what was these PR aimed at solving?

**Comment by saikatsardar01** [comment]
I have mentioned in a issue. Please check

**Pull request closed without merging**
