### PR TITLE
Added the function for disabling the buttons while fetching AI quotes from server

### PR DESCRIPTION
**Pull request by HP200421**
- Added class to toggle between button disabled and cursor not allowed
- Standard apporach to disable the buttons while fetching data
- Dark mode will not have any effect of this

### CODE REVIEW

**Review by DanonymousCoder — APPROVED** [review]
Nice! but next time follow the CONTRIBUTING.md guidelines

**Comment by DanonymousCoder** [comment]
Also, don't forget to star the repo! Thank you

**Comment by HP200421** [comment]
Sorry about CONTRIBUTING.md guidelines.
I will take care of that from next time.

**Comment by DanonymousCoder** [comment]
Also, don't forget to star the repo! Thank you

**Pull request merged**
